server:
  port:
    8080
spring:
  datasource:
    password: test
    url: jdbc:h2:mem:testdb
    username: test
    driver-classname: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
age_limit: 18